import pandas as pd
import matplotlib.pyplot as plt

print('----------------------Mergulho mais profundo dos animais----------------------')
divers = pd.read_csv('csv/deepest-diving-animals.csv')
print(divers)
print('----------------------Espécies----------------------')
print(divers['category'].value_counts())
print('----------------------Máximo de profundidade por espécie----------------------')
max_depths = divers.groupby('category')['depth'].max()
print(max_depths)
print('----------------------Criando coluna  max_depth----------------------')
df = max_depths.reset_index(name ='max_depth')
print(df)
print('----------------------Gráfico de barras----------------------')
plt.bar(df['category'], df['max_depth'])
plt.xlabel('Espécie')
plt.ylabel('Profundidade Máxima (m)')
plt.show()
print('----------------------Gráfico de barra horizontal    ----------------------')
plt.barh(df['category'], df['max_depth'])
plt.xlabel('Profundidade Máxima (m)')
plt.ylabel('Espécie')
plt.show()
print('----------------------Ordernar para gráfico----------------------')
df_sorted = df.sort_values('max_depth')
print(df_sorted)
plt.barh(df_sorted['category'], df_sorted['max_depth'])
plt.xlabel('Profundidade Máxima (m)')
plt.ylabel('Espécie')
plt.show()

print('----------------------estilizando o gráfico----------------------')

def clean_bar_axes():
    ax = plt.gca()
    ax.spines[['top', 'right', 'bottom', 'left']].set_visible(False)
    ax.grid(axis='x', linestyle='--', alpha=0.5)
    ax.tick_params(axis='both', length=0)
plt.xlabel('Profundidade Máxima (m)')
plt.ylabel('Espécie')
clean_bar_axes()
plt.show()